#!/bin/bash

set -ex
set -o xtrace

export DEBIAN_FRONTEND=noninteractive



systemctl enable cassandra.service

#systemctl stop cassandra

#rm -rf /var/lib/cassandra/data

#sudo mkdir /var/lib/cassandra/data

#sudo chown cassandra:cassandra -R /var/lib/cassandra

systemctl start cassandra.service
